#!/usr/bin/env python

import random
import sys
import re

dieinput = raw_input('State the Number of Dice to be rolled as NdD (eg, if rolling two six-sided dice, enter 2d6): ')

if re.match('^[0-9]*[dD][0-9]*$', dieinput) is None:
    sys.exit('Please enter only in NdD format (eg, if rolling 3 eight-sided dice, enter 3d8). You\'ll have to start over now.')

##Test line to confirm entered input.
#print 'You are rolling ' + dieinput

if 'd' in dieinput:
    dielist = dieinput.split('d')
elif 'D' in dieinput:
    dielist = dieinput.split('D')
    
##Test line to confirm die splitting.
#print dielist

dienumber = int(dielist[0])
diesize = int(dielist[1])

##Test lines to confirm indexing.
#print "Number of dice: " + str(dienumber)
#print "Size of dice: " + str(diesize)

##Old method for producing results. Doesn't support seeing result of individual die rolls.
#result = 0
#for _ in range(dienumber):
#    result = result + random.randint(1,diesize) 
#print 'Result: ' + str(result)
 
dielist = []
for _ in range(dienumber):
    dielist.append(random.randint(1,diesize))

dietotal = sum(dielist)

print 'Rolls: ', dielist, 'Total: ' + str(dietotal)

##used for doing a single 'die' for entire range, less correct
#integerstart = dienumber
#
#integerend = diesize * dienumber
#
#Test line to confirm simple math.
#print 'will produce integer between ' + str(integerstart) + ' and ' + str(integerend)
#print 'Result: ' + str(random.randint(integerstart,integerend))